stages:
  - webhook

update:
  stage: webhook
  script:
    - curl -d { "state":"updated" } -X POST https://396e-84-88-188-229.ngrok-free.app/webhooks
  rules:
    - changes:
        - licenses/*
      when: on_success
