version : "3.6"

services :
  license-mapping-app:
    image: emartps/license-mapping-api:latest
    container_name: license-mapping-app
    volumes:
      - /home/user/.ssh/authorized_keys:/root/.ssh/id_rsa
    env_file:
      - .env
    ports:
      - "8000:8000"
