version : "3.6"

services :
  license-mapping-app:
    image: emartps/license-mapping-api:latest
    container_name: license-mapping-app
    env_file:
      - .env
    ports:
      - "8000:8000"
  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NO_RESTART=false
      - WATCHTOWER_TIMEOUT=30s
      - WATCHTOWER_SCHEDULE=5 * * * * *
      - WATCHTOWER_DEBUG=false
      - TZ=Europe/Madrid
    network_mode: bridge
