version : "3.6"

services :
  license-mapping-app:
    image: emartps/license-mapping-api:main
    container_name: license-mapping-app
    volumes:
      - /home/user/.ssh/:/root/.ssh/
    env_file:
      - .env
    ports:
      - "8000:8000"

