run-name: update-database

on:
  push:
    paths:
      - 'licenses/*'

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - run: curl -H "Content-Type:application/json" --data @data.json https://gitlab.bsc.es/inb/elixir/software-observatory/license-mapping-api/webhooks
      
   
